import { App } from 'vue';
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faBars,
  // faCog,
  // faCheck,
  // faEnvelope,
  // faComment,
  // faAddressBook,
  // faBolt,
  // faPlusCircle,
  // faCartPlus,
  // faIdBadge,
  // faDragon,
  // faReceipt,
  // faScroll,
  // faTicketAlt,
  // faDesktop,
  // faFileContract,
  // faCircle,
  // faArrowLeft,
  // faUser,
  // faUserTag,
  // faUserCheck,
  // faServer,
  // faChartArea,
  // faChartBar,
  // faChartLine,
  // faDatabase,
  // faClipboardCheck,
  // faLink,
  // faAddressCard,
  // faBarcode,
  // faSimCard,
  // faQuestion,
  // faFileInvoice,
  // faEdit,
  // faLock,
  // faHeadset,
  // faWrench,
  // faCommentDots,
  // faShare,
  // faScrewdriverWrench,
  // faTags,
  // faFireFlameCurved,
  // faSliders,
  // faUserShield,
  // faUserSlash,
  // faUsersRays,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faBars,
  // faCog,
  // faCheck,
  // faEnvelope,
  // faComment,
  // faAddressBook,
  // faBolt,
  // faPlusCircle,
  // faCartPlus,
  // faIdBadge,
  // faDragon,
  // faReceipt,
  // faScroll,
  // faTicketAlt,
  // faDesktop,
  // faFileContract,
  // faCircle,
  // faArrowLeft,
  // faUser,
  // faUserTag,
  // faUserCheck,
  // faServer,
  // faChartArea,
  // faChartBar,
  // faChartLine,
  // faDatabase,
  // faClipboardCheck,
  // faLink,
  // faAddressCard,
  // faBarcode,
  // faSimCard,
  // faQuestion,
  // faFileInvoice,
  // faEdit,
  // faLock,
  // faHeadset,
  // faWrench,
  // faCommentDots,
  // faShare,
  // faScrewdriverWrench,
  // faTags,
  // faFireFlameCurved,
  // faSliders,
  // faUserShield,
  // faUserSlash,
  // faUsersRays
);

const FontIcon = {
  install(app: App) {
    app.component('fa-icon', FontAwesomeIcon);
    app.component('font-awesome-icon', FontAwesomeIcon);
  },
};

export default FontIcon;
